package com.RestAPITest;

import org.testng.Assert;
import org.testng.annotations.Test;

import io.restassured.response.Response;

import static io.restassured.RestAssured.given;
/*
 * given():Set Prerequisite
 * ---------------------
 * header,cookie,query parameter and path parameter, Request Payload,Authorization
 * 
 * when(): Request type+ endpoint
 * ---------------------------------
 * GET,POST,PUT,PATCH,DELETE
 * 
 * then(): validate response
 * -------------------------------
 * status code,message,response time, response payload,header,cookies
 */
public class TestCookies_Header {
  @Test
  public void testCookies() 
  {
	  Response res=given()
	  .when().get("https://www.google.com");
	  
	  
	  //get all cookies in console
	  res.then().log().cookies();
	  
	  /*
	   * Cookies are generated by server 
	   * Cookies are dynamic
	   * Two cookies should not have same value
	   * 
	   */
	  
	  //how to get single cookie details
	 String actCookie= res.getCookie("AEC");
	 String expCookie="AVh_V2gAkkELK46N9g9DHIKINNEoJG8-VARYJ3Te0AIlRHl4wt7kz-yqIoQ;";
	 
	 //actual cookie should not contains exp cookie
	 
//	 Assert.assertFalse(actCookie.contains(expCookie),"Test fail as cookies values are same");
//	 System.out.println("Tets Pass as cookies values are not same");
//	 
	 
	 Assert.assertTrue(!(actCookie.contains(expCookie)));
	 System.out.println("Test Pass as cookies values are not same");
	 
	 	  
  }
  
  @Test
  public void testHeader()
  {
	  
	  Response res=given()
	  .when().get("https://www.google.com");
	  
	  
	  //get all header in console
	  res.then().log().headers();
	  
	  //get the single header value
	 String actHeader=res.getHeader("Content-Type");
	 System.out.println("Value is: "+actHeader);
	 
	 String exp="text/html; charset=ISO-8859-1";
	 
	 Assert.assertEquals(actHeader,exp);
	 System.out.println("Test Pass!");
	  
  }
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
}
